version: "3.9"

services:
  composer:
    image: composer:2.3.5
    restart: "no"
    volumes:
      - ./project:/app
    entrypoint: "composer install"
#  php:
#    image: php:7.4.29-cli
#    restart: "no"
#    volumes:
#      - ./project:/app
#    working_dir: /app
  php-fpm:
    image: php:7.4.29-fpm
    container_name: php
    working_dir: /app
    volumes:
      - ./project:/app
  nginx:
    image: nginx:1.21.6-alpine
    container_name: nginx
    working_dir: /app
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./project:/app
      - ./docker/log/nginx:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
